Fixes xy coordinate data extract from cyme converter
arras-energy/gridlabd pull request #111
Opened 2023-10-04 04:12 UTC by MitchellAV

This commit fixes #46

2023-10-10 18:58 UTC, MitchellAV commented
@dchassin I'll take a look. I think I know what happened

2023-10-11 14:13 UTC, dchassin requested changes
See comments on autotests: remove check for mdb-schema. This should no longer be needed and it doesn't work on all platforms anyway.

2023-10-11 14:13 UTC, dchassin commented on converters/autotest/test_mdb2glm_xy_coordinates.glm
Recommend not testing for `mdb-schema` missing anymore. 
1. `apt install mdbtools` doesn't always install it in the same folder on different platforms.
2. mdbtools should always be installed anyway.

2023-10-11 14:13 UTC, dchassin commented on converters/autotest/test_mdbtable2glm.glm
See above comment about testing for mdb-schema.

2023-10-11 14:13 UTC, dchassin commented on converters/autotest/test_mdbtable2glmobject.glm
See above comment about testing for mdc-schema.

2023-10-12 01:23 UTC, dchassin approved these changes

2023-10-12 01:23 UTC, merged